 name: 多看点

 on:
   workflow_dispatch:
   schedule:
     - cron: '0 8 * * *'
   watch:
     types: started
   repository_dispatch:
     types: _

 jobs:
   build:
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     steps:
       - name: Use Node.js 12.x
         uses: actions/setup-node@v1
         with:
           node-version: 12.x
       - name: npm install
         run: |
           cd ~/action-group
           npm install
       - name: '运行 【多看点】'
         run: |
           cd ~/action-group
           node Node/sqxs.js
