# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 汽车之家极速版

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'
  watch:
    types: started
  repository_dispatch:
    types: qczjspeed
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: shitou12/QCZJSPEED
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: '运行 【汽车之家极速版】'
        run: |
          node Task/qczjspeed.js
    env:
        QCZJ_GetUserInfoURL: ${{ secrets.QCZJ_GetUserInfoURL }}
        QCZJ_GetUserInfoHEADER: ${{ secrets.QCZJ_GetUserInfoHEADER }}
        QCZJ_coinBODY: ${{ secrets.QCZJ_coinBODY }}
        QCZJ_taskBODY: ${{ secrets.QCZJ_taskBODY }}		
        QCZJ_activityBODY: ${{ secrets.QCZJ_activityBODY }}	
        QCZJ_GoldcoinBODY: ${{ secrets.QCZJ_GoldcoinBODY }}	
        QCZJ_videoBODY: ${{ secrets.QCZJ_videoBODY }}	        
        QCZJ_WelfarevideoBODY: ${{ secrets.QCZJ_WelfarevideoBODY }}	
        QCZJ_WelfareBODY: ${{ secrets.QCZJ_WelfareBODY }}	
        QCZJ_addCoinBODY: ${{ secrets.QCZJ_addCoinBODY }}
        QCZJ_addCoin2BODY: ${{ secrets.QCZJ_addCoin2BODY }}
        QCZJ_reportAssHEADER: ${{ secrets.QCZJ_reportAssHEADER }}
        QCZJ_reportAssBODY: ${{ secrets.QCZJ_reportAssBODY }}
        QCZJ_cointowalletBODY: ${{ secrets.QCZJ_cointowalletBODY }}
        QCZJ_CASH: ${{ secrets.QCZJ_CASH }}
